### ISSUE TITLE
 Is it possible to get the drive ID url of the uploaded file?

### ISSUE THREAD

**Issue by dycross** [tanaikech/AsynchronousResumableUploadForGoogleDrive#1]
Hi Tanaike and people!,
I am doing great the code so far, but I am trying to get the url of the file I upload in GAS to be able to paste it into a cell that I choose from google sheet, is this possible ?, I understand that in "fields" of resource could If the ID is specified, also try adding "fr.readAsDataURL (file);", although without success. Could you help me?

**Comment by tanaikech** [comment]
Yes. It can be achieved. For this, I updated the sample script. Please check it.

https://github.com/tanaikech/AsynchronousResumableUploadForGoogleDrive#v101

In this updated, the file information is sent to Google Apps Script side. You can retrieve the URL of the file from it.

**Comment by dycross** [comment]
This work perfect to me!, thanks a lot for your help tanaikech you are awesome
